# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 646ed5f3134d7fbe910f1a41179669d180870c3b4ec0ce724b40de03840d6413d287ec6f4922149820d1dc36c9e39bf2259f2c236584f80296e8b44a9a957d12

test:
  secret_key_base: fc0b646da658e2a24a57248abdd0d212b093b9c2d707298bfdeb291c20eb9f45ae28bf74d8e5c78282097f0fb7284642a5df0901d6d14fc2cb79b6cba5750acf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
